//COMMON
export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';

//AUTH
export const USER_TOKEN = 'USER_TOKEN';
export const USER_DATA = 'USER_DATA';
export const USER_EXIST_DATA = 'USER_EXIST_DATA';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';

//CONFERENCIA
export const CONFERENCIA_COD='CONFERENCIA_COD';

//SI TE LO PERDISTE
export const SI_TE_LO_PERDISTE_LIST='SI_TE_LO_PERDISTE_LIST';